import ESieve
import time


def is_prime(num, primelist):
    return num in primelist


timeStart = time.time()

prime_list = ESieve.primes_sieve(8000)
b_pos = ESieve.primes_sieve(1000)

n_max = 0
a_max = 0
b_max = 0

for a in range(-999, 1000):
    for b in b_pos:
        n = 0

        while is_prime(n**2 + a*n + b, prime_list):
            n += 1

        if n > n_max:
            n_max = n
            a_max = a
            b_max = b

result = 'A sequence length of {} is generated by the coefficients a: {}, b: {}, which have the product of {}' \
    .format(n_max, a_max, b_max, a_max * b_max)

print(result)
print('Process took: ' + str(time.time()-timeStart) + " s")







